<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>14.0</LangVersion>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <RootNamespace>SpaceInvaders</RootNamespace>
    <AssemblyName>SpaceInvaders</AssemblyName>
    <WarningLevel>4</WarningLevel>
    <Deterministic>true</Deterministic>
    <Nullable>disable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Audio\click.wav" />
    <None Remove="Resources\Audio\game.wav" />
    <None Remove="Resources\Audio\mainmenu.wav" />
    <None Remove="Resources\Images\enemy1_0.png" />
    <None Remove="Resources\Images\enemy1_1.png" />
    <None Remove="Resources\Images\enemy2_0.png" />
    <None Remove="Resources\Images\enemy2_1.png" />
    <None Remove="Resources\Images\enemy3_0.png" />
    <None Remove="Resources\Images\enemy3_1.png" />
    <None Remove="Resources\Images\enemyprojectile.png" />
    <None Remove="Resources\Images\heartempty.png" />
    <None Remove="Resources\Images\heartfull.png" />
    <None Remove="Resources\Images\pickup_heart_0.png" />
    <None Remove="Resources\Images\pickup_heart_1.png" />
    <None Remove="Resources\Images\pickup_points_0.png" />
    <None Remove="Resources\Images\pickup_points_1.png" />
    <None Remove="Resources\Images\pickup_shield_0.png" />
    <None Remove="Resources\Images\pickup_shield_1.png" />
    <None Remove="Resources\Images\pickup_shoot_0.png" />
    <None Remove="Resources\Images\pickup_shoot_1.png" />
    <None Remove="Resources\Images\pickup_shoot_2.png" />
    <None Remove="Resources\Images\pickup_shoot_3.png" />
    <None Remove="Resources\Images\player.png" />
    <None Remove="Resources\Images\playerprojectile.png" />
    <None Remove="Resources\Images\shieldempty.png" />
    <None Remove="Resources\Images\shieldfull.png" />
    <None Remove="Resources\Images\specialattack.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>

    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>

    <Content Include="Resources\Audio\click.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Audio\game.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\enemy1_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\enemy1_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\enemy2_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\enemy2_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\enemy3_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\enemy3_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\heartempty.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\heartfull.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\pickup_heart_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\pickup_heart_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\pickup_points_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\pickup_points_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\pickup_shield_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\pickup_shield_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\pickup_shoot_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\pickup_shoot_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\pickup_shoot_2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\pickup_shoot_3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\player.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\shieldempty.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\shieldfull.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\specialattack.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Resource Include="Resources\Fonts\Pixel Digivolve.otf" />

    <Content Include="Resources\Images\enemyprojectile.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Images\playerprojectile.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="Resources\Audio\explosion.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Audio\hover.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Audio\mainmenu.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Audio\pickup.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Audio\shoot.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    
    <None Update="App.config" />
  </ItemGroup>

</Project>
